name-template: '$NEXT_MAJOR_VERSION'
tag-template: '$NEXT_MAJOR_VERSION'
categories:
  - title: '🧬 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🏎 Performance Tweaks'
    labels:
      - 'performance'
  - title: '🎨 Style Tweaks'
    labels:
      - 'style tweak'
  - title: '📘 Documentation'
    labels:
      - 'documentation'
  - title: '🧹 Cleanup'
    labels:
      - 'cleanup'
  - title: '👷‍♀️ Testing, Configuration & Deployment'
    labels:
      - 'devops'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'dependencies'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes

  $CHANGES

  ## 🕵️‍♀️ Full commit logs

  - https://github.com/oncokb/styles/compare/$PREVIOUS_TAG...$NEXT_MAJOR_VERSION
