name: Application CI
on: [ push, pull_request ]
jobs:
  applications:
    name: CI suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.16.1
      - name: Install node.js packages
        run: npm install
      - name: Package application
        run: gulp build
